global using ZAMY.Application;
global using ZAMY.Infrastructure;
global using System.Linq.Expressions;
global using Microsoft.EntityFrameworkCore.Query;
global using Bookify.Domain.Consts;
global using System.Net;
global using Microsoft.AspNetCore.Mvc;
global using ZAMY.Application.Services.Meals;
global using ZAMY.Domain.Entities;
